<?php

/**
 * Prevent Direct Access
 *
 * @since 0.1
 */
defined( 'ABSPATH' ) or die( "Restricted access!" );

/**
 * Register text domain
 *
 * @since 4.6
 */
function smbtoolbar_textdomain() {
    load_plugin_textdomain( SMEDIABT_TEXT, false, SMEDIABT_DIR . '/languages/' );
}
add_action( 'init', SMEDIABT_PREFIX . '_textdomain' );

/**
 * Print direct link to plugin admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the plugin admin page
 *
 * @since  4.6
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function smbtoolbar_settings_link( $links ) {
    $page = '<a href="' . admin_url( 'options-general.php?page=' . SMEDIABT_SLUG . '.php' ) .'">' . __( 'Settings', SMEDIABT_TEXT ) . '</a>';
    array_unshift( $links, $page );
    return $links;
}
add_filter( 'plugin_action_links_' . SMEDIABT_BASE, SMEDIABT_PREFIX . '_settings_link' );

/**
 * Print additional links to plugin meta row
 *
 * @since 4.6
 */
function smbtoolbar_plugin_row_meta( $links, $file ) {

    if ( strpos( $file, SMEDIABT_SLUG . '.php' ) !== false ) {

        $new_links = array(
                           'donate' => '<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8A88KC7TFF6CS" target="_blank"><span class="dashicons dashicons-heart"></span> ' . __( 'Donate', SMEDIABT_TEXT ) . '</a>'
                           );
        $links = array_merge( $links, $new_links );
    }

    return $links;
}
add_filter( 'plugin_row_meta', SMEDIABT_PREFIX . '_plugin_row_meta', 10, 2 );

/**
 * Register plugin's submenu in the "Settings" Admin Menu
 *
 * @since 4.6
 */
function smbtoolbar_register_submenu_page() {
    $menu_title = __( 'Social Media Follow Buttons', SMEDIABT_TEXT );
    $capability = 'manage_options';
    add_options_page( SMEDIABT_NAME, $menu_title, $capability, SMEDIABT_SLUG, SMEDIABT_PREFIX . '_render_submenu_page' );
}
add_action( 'admin_menu', SMEDIABT_PREFIX . '_register_submenu_page' );

/**
 * Register settings
 *
 * @since 4.6
 */
function smbtoolbar_register_settings() {
    register_setting( SMEDIABT_SETTINGS . '_settings_group', SMEDIABT_SETTINGS . '_settings' );
    register_setting( SMEDIABT_SETTINGS . '_settings_group', SMEDIABT_SETTINGS . '_service_info' );
}
add_action( 'admin_init', SMEDIABT_PREFIX . '_register_settings' );
